#ifndef MESSAGE_TYPES_H
#define MESSAGE_TYPES_H

enum class Status
{
    SUCCESS = 0,
    ERROR = 1,
};

enum class Flag
{
    NO = 0,
    YES = 1
};

enum class FriendRequestState
{
    REJECTED = 0,
    ACCEPTED = 1,
};

enum class FriendshipState
{
    FRIEND = 0,
    PENDING = 1,
    NOT_FRIEND = 2,
};

enum class MessageType
{
    LOGIN_REQUEST = 101,
    LOGIN_RESPONSE = 102,

    SIGN_UP_REQUEST = 103,
    SIGN_UP_RESPONSE = 104,

    LOGOUT_REQUEST = 105,
    LOGOUT_RESPONSE = 106,

    SEARCH_USER_REQUEST = 107,
    SEARCH_USER_RESPONSE = 108,

    FRIEND_REQ_REQUEST = 109,
    FRIEND_REQ_RESPONSE = 110,

    ///// server will send this messages when user logged into the account
    USER_PROFILE_INFORMATION = 111,
    USER_FRIENDS_LIST = 112,
    USER_PENDING_FRIEND_REQUESTS_LIST = 113,
    USER_MESSAGE_HISTORY = 114,
    /////

    CHANGE_PASSWORD_REQUEST = 115,
    CHANGE_PASSWORD_RESPONSE = 116,

    RECONNECT_REQUEST = 117,
    RECONNECT_RESPONSE = 118,

    UPDATE_PROFILE_REQUEST = 119,
    UPDATE_PROFILE_RESPONSE = 120,

    TOKEN_LOGIN_REQUEST = 121,
    TOKEN_LOGIN_RESPONSE = 122,

    FORCED_LOGOUT = 123,

    CHAT_MESSAGE = 124,
    
    GET_CHAT_MESSAGE_ID_REQUEST = 125,
    GET_CHAT_MESSAGE_ID_RESPONSE = 126
};

#endif //MESSAGE_TYPES_H
